export const Text = '#222'
export const White = '#FFF'
export const OffWhite = '#F3F3F3'
export const Primary = '#32906c'
export const Secondary = '#fff2d8'
export const Tertiary = '#ee6c52'
export const Grey = '#727272'
export const LightGrey = '#F2F2F2'
export const BorderGrey = '#AFAFAF'
export const ErrorRed = '#FF2C2C'
export const WarningOrange = '#F87D0B'

export const Background = '#D0DBF6'
export const OnBackground = '#B0C7FF'

export const Meat = '#ccab9f'
export const Veg = '#8ab563'
export const Fruit = '#fd8664'
export const Dairy = '#e0e6e6'
export const Juice = '#fabe0e'
export const Baked = '#edddc3'
export const Snacks = '#b7a5d9'

